name: 'Upload Kotlin spec artifacts'
runs:
  using: 'composite'
  steps:
    - name: 'Upload Kotlin spec PDF artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: kotlin-spec-pdf
        path: |
          build/spec/pdf/
    - name: 'Upload Kotlin spec HTML artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: kotlin-spec-html
        path: |
          build/spec/html/
