import at.phatbl.shellexec.ShellExec
import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import java.io.File
import java.net.URI
import java.util.regex.Pattern

plugins {
    idea
    id("org.jetbrains.intellij.platform") version "2.10.5"
    antlr
    `maven-publish`
    kotlin("jvm")
    id("at.phatbl.shellexec")
}

group = "org.jetbrains.kotlin.spec.grammar"
version = "0.1"

val archivePrefix = "kotlin-grammar-parser"
val generatedGrammarSources = layout.buildDirectory.dir("generated-src/antlr/main")
val grammarProjectDir = projectDir
val grammarTestDataDir = layout.projectDirectory.dir("testData").asFile

repositories {
    intellijPlatform {
        defaultRepositories()
    }
    maven {
        url = URI("https://packages.jetbrains.team/maven/p/plan/apal")
    }
    mavenCentral()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = group as String
            artifactId = archivePrefix
            version = version as String

            from(components["java"])
        }
    }
}

sourceSets {
    main {
        // Parser sources are generated by ANTLR and added to this source set by the ANTLR plugin.
        // Do not compile ignored, stale generator output that may remain under src/main/java.
        java.setSrcDirs(listOf(generatedGrammarSources))
    }
    test {
        java.srcDir("src/test")
    }
}

dependencies {
    implementation("junit:junit:4.13.2")
    antlr("org.antlr:antlr4:4.13.1")
    intellijPlatform {
        intellijIdeaCommunity("2022.3")
        javaCompiler()
        testFramework(TestFrameworkType.Platform)
    }
}

tasks.compileKotlin {
    dependsOn("generateGrammarSource")
}

java {
    targetCompatibility = JavaVersion.VERSION_11
}

kotlin {
    jvmToolchain(11)
}

tasks.withType<AntlrTask> {
    outputDirectory = generatedGrammarSources.get().asFile

    arguments.add("-package")
    arguments.add("org.jetbrains.kotlin.spec.grammar")
}

tasks.register("removeFailedMarkerFiles") {
    doFirst {
        grammarTestDataDir
            .walkTopDown()
            .filter { it.isFile && it.extension == "failed" }
            .forEach { it.delete() }
    }
}

tasks.withType<Test> {
    dependsOn("removeFailedMarkerFiles")

    workingDir = grammarProjectDir
    ignoreFailures = project.hasProperty("teamcity")

    systemProperties["TEST_PATH_FILTER"] = System.getProperty("TEST_PATH_FILTER")
}

tasks.register("removeCompilerTestData") {
    doFirst {
        grammarTestDataDir.walkTopDown().forEach {
            if (!it.name.endsWith("antlrtree.txt"))
                it.delete()
        }
    }
}

tasks.register<ShellExec>("downloadCompilerTests") {
    doFirst {
        workingDir = grammarProjectDir
        command = grammarProjectDir.resolve("scripts/build/downloadCompilerTests.sh").readText()
    }
}

tasks.register("syncWithCompilerTests") {
    doFirst {
        grammarTestDataDir.walkTopDown().forEach {
            if (it.name.endsWith("antlrtree.txt") && !File("${it.parent}/${it.name.substringBefore(".antlrtree.txt")}.kt").exists())
                it.delete()
        }
    }
}

tasks.register("prepareDiagnosticsCompilerTests") {
    doFirst {
        //language=RegExp
        val rangeStartOrEndPattern = Pattern.compile("(<!(([^>])|((?<!\\!)\\>))+!>)|(<!>)")
        val filePattern = Pattern.compile("""// ?FILE: ?""")
        val ls = System.lineSeparator()
        val sourceCodeByFilePattern =
            Pattern.compile("""^(?<filename>.*?)\.(?<extension>kts?|java)($ls)*(?<code>[\s\S]*)$""")

        grammarTestDataDir.resolve("diagnostics").walkTopDown().forEach {
            println("Processing file $it")
            if (it.name.endsWith(".fir.kt")) {
                it.delete()
            } else if (it.extension == "kt") {
                val sourceCode = it.readText()
                val sourceCodeByFiles = sourceCode.split(filePattern)

                if (sourceCodeByFiles.size > 1) {
                    sourceCodeByFiles.forEachIndexed { index, content ->
                        if (index == 0)
                            return@forEachIndexed

                        val matcher = sourceCodeByFilePattern.matcher(content).apply { find() }
                        val filename = matcher.group("filename").replace("/", "_")
                        val extension = matcher.group("extension")
                        val code = matcher.group("code")

                        if (extension == "kt" || extension == "kts")
                            File("${it.parent}/${it.nameWithoutExtension}.$filename.$extension").writeText(
                                rangeStartOrEndPattern.matcher(code).replaceAll("")
                            )
                    }
                    it.delete()
                } else {
                    it.writeText(rangeStartOrEndPattern.matcher(it.readText()).replaceAll(""))
                }
            } else if (!it.name.endsWith("antlrtree.txt")) {
                it.delete()
            }
        }
    }
}

tasks.withType<Jar> {
    archiveFileName.set("$archivePrefix-${archiveVersion.get()}.jar")

    manifest {
        attributes(
            mapOf(
                "Class-Path" to configurations.runtimeClasspath.get().files.joinToString(" ") { it.name }
            )
        )
    }

    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from(configurations.runtimeClasspath.get().files.map { if (it.isDirectory) it else zipTree(it) })
}
