name: 'Build Kotlin spec on PRs (version 2)'

on: [pull_request]

jobs:
  build-spec:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Build Kotlin spec in its Docker container'
        uses: ./.github/actions/build-spec-in-docker
