name: Build Kotlin spec on PRs

on: [pull_request]

jobs:
  build-spec:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Setup pandoc
        env:
          PANDOC_VERSION: 2.14.2
          PANDOC_DEB: pandoc-2.14.2-1-amd64.deb
        run: |
          curl -sLO https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/$PANDOC_DEB
          sudo dpkg -i $PANDOC_DEB
          rm $PANDOC_DEB
      - name: Setup Kotlin spec dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gpp
          sudo apt-get install -y librsvg2-bin
          sudo apt-get install -y npm
          curl -sL https://deb.nodesource.com/setup_18.x | bash -
          sudo apt-get install -y nodejs
          sudo apt-get install -y --no-install-recommends texlive-latex-extra
          sudo apt-get install -y --no-install-recommends texlive-fonts-extra
          sudo apt-get install -y --no-install-recommends texlive-bibtex-extra
          sudo apt-get install -y --no-install-recommends texlive-science
          sudo apt-get install -y --no-install-recommends fontconfig
          sudo apt-get install -y --no-install-recommends lmodern
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build Kotlin spec
        run: |
          ./gradlew buildPdf buildWeb
      - name: Smoke test Kotlin grammar
        run: |
          ./gradlew :grammar:jar
